name: Deploy ASP.NET MVC App deploy to Azure Web App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  AZURE_WEBAPP_FRONTEND: 'contoso-webapp'
  AZURE_WEBAPP_NAME: 'contoso-api'    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1' 
  working-directory: ./src/Contoso.WebApi        # set this to the dot net version to use
  working-directory-frontend: ./src/Contoso.Web

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - name: divide error
        run: echo "Hello lekhika"
        
  gitIssueCreation:
    name: Git Creation Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Git Creation Demo
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_COMMIT_SHA: ${{ github.sha }}
          # GITHUB_REPO_OWNER: 'lekhika13'
          GITHUB_OWNER: 'lekhika13'
          GITHUB_REPOSITORY: 'hackathon'
          GITHUB_ISSUE_TITLE: 'Facing issue with Divide Error'
          GITHUB_ISSUE_BODY: 'PLease check'
      - name: Update npm packages
        uses: technote-space/create-pr-action@v2
        with:
          # EXECUTE_COMMANDS: |
          #   npx npm-check-updates -u --packageFile package.json
          #   yarn install
          #   yarn upgrade
          #   yarn audit
          COMMIT_MESSAGE: 'chore: update npm dependencies'
          COMMIT_NAME: 'GitHub Actions'
          COMMIT_EMAIL: 'example@example.com'
          PR_BRANCH_NAME: 'feature-${PR_ID}'
          PR_TITLE: 'chore: update npm dependencies'